# Generated by Django 5.1.1 on 2024-09-20 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_appointment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="medication_regimen",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_appointment",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
