# Generated by Django 5.1.1 on 2024-09-20 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_patient_user_patient_doctor_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="patient",
            name="doctor_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_appointment",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_condition",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="next_appointment",
        ),
        migrations.AddField(
            model_name="patient",
            name="medication_frequency",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_condition", models.TextField(blank=True, null=True)),
                (
                    "last_appointment",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "next_appointment",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("reason", models.CharField(max_length=255, null=True)),
                ("doctor_notes", models.CharField(max_length=255, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="chat.patient",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="chat.doctor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="chat.doctor",
            ),
            preserve_default=False,
        ),
    ]
